name: Deploy 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: frontend deps
        run: |
          cd tunet-ellenorzo
          npm install

      - name: build
        run: |
          cd tunet-ellenorzo
          ng build --prod

      - name: deploy frontend
        run: |
          cd tunet-ellenorzo
          firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: backend deps
        run: |
          cd tunet-ellenorzo_backend/functions
          npm install

      - name: deploy backend
        run: |
          cd tunet-ellenorzo_backend
          firebase deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
